- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--image=gcr.io/neon-airway-224101/://github.com'
  - '--filename=./deployment-1.yaml'
  - '--location=us-east4'
  - '--cluster=gke-deployment-cluster'
